export const bookConstants = {

    GET_BOOK_BY_ID_REQUEST: ' GET_BOOK_BY_ID_REQUEST',
    GET_BOOK_BY_ID_SUCCESS: ' GET_BOOK_BY_ID_SUCCESS',
    GET_BOOK_BY_ID_FAILURE: ' GET_BOOK_BY_ID_FAILURE',

    GET_BOOKS_REQUEST: ' GET_BOOKS_REQUEST',
    GET_BOOKS_SUCCESS: ' GET_BOOKS_SUCCESS',
    GET_BOOKS_FAILURE: ' GET_BOOKS_FAILURE'





}


