export const userConstants = {

    USER_SIGNUP_REQUEST: ' USER_SIGNUP_REQUEST',
    USER_SIGNUP_SUCCESS: ' USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILURE: ' USER_SIGNUP_FAILURE',

    USER_LOGIN_REQUEST: ' USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: ' USER_LOGIN_SUCCESS',
    USER_LOGIN_FAILURE: ' USER_LOGIN_FAILURE',

    GET_USER_DATA_REQUEST: ' GET_USER_DATA_REQUEST',
    GET_USER_DATA_SUCCESS: ' GET_USER_DATA_SUCCESS',
    GET_USER_DATA_FAILURE: ' GET_USER_DATA_FAILURE',


    UPDATE_USER_REQUEST: ' UPDATE_USER_REQUEST',
    UPDATE_USER_SUCCESS: ' UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: ' UPDATE_USER_FAILURE'


}


